version: '3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      
  wordpress:
    depends_on:
      - db
    image: wordpress:fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
      
  webserver:
    depends_on:
      - wordpress
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
      
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html -d talhayıldızdeneme.com
    volumes:
      - ./certs:/etc/letsencrypt
    restart: always
